[2021-05-26 10:00:50 -0700] [6137] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:00:50 -0700] [6138] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:00:50 -0700] [6139] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:01:18 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6137)
[2021-05-26 10:01:18 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6138)
[2021-05-26 10:01:18 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6139)
[2021-05-26 10:01:20 -0700] [6148] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:01:20 -0700] [6149] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:01:20 -0700] [6150] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:01:49 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6148)
[2021-05-26 10:01:49 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6149)
[2021-05-26 10:01:49 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6150)
[2021-05-26 10:01:50 -0700] [6156] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:01:50 -0700] [6157] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:01:51 -0700] [6158] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:02:19 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6156)
[2021-05-26 10:02:19 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6157)
[2021-05-26 10:02:19 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6158)
[2021-05-26 10:02:21 -0700] [6163] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:02:21 -0700] [6164] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:02:21 -0700] [6165] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:02:49 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6163)
[2021-05-26 10:02:49 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6164)
[2021-05-26 10:02:49 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6165)
[2021-05-26 10:02:51 -0700] [6169] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:02:51 -0700] [6170] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:02:51 -0700] [6171] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:03:19 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6169)
[2021-05-26 10:03:19 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6170)
[2021-05-26 10:03:19 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6171)
[2021-05-26 10:03:21 -0700] [6176] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:03:21 -0700] [6177] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:03:21 -0700] [6178] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:03:49 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6176)
[2021-05-26 10:03:49 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6177)
[2021-05-26 10:03:49 -0700] [6134] [CRITICAL] WORKER TIMEOUT (pid:6178)
[2021-05-26 10:03:51 -0700] [6182] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:03:51 -0700] [6183] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
[2021-05-26 10:03:51 -0700] [6184] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in check_templates_exist
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 62, in <listcomp>
    [app.jinja_env.get_template(try_this) for try_this in try_these]
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ldnlab/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ldnlab/.local/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: thanks-mturksubmit.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/home/ldnlab/.local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 71, in <module>
    check_templates_exist()
  File "/home/ldnlab/.local/lib/python3.6/site-packages/psiturk/experiment.py", line 65, in check_templates_exist
    f"Missing one of the following templates: {', '.join(try_these)}."
RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.Copy these over from a freshly-created psiturk example experiment.('TemplateNotFound', 'thanks-mturksubmit.html')
